name: git_config
description: A Dart CLI to fetch config files from a remote Git repository into the project.
version: 1.0.0
publisher: ttankkeo112@gmail.com
repository: https://github.com/MTtankkeo/git_config

environment:
  sdk: '>=3.0.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  args: ^2.7.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
